name: check main branch

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: set up JDK 16
      uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: '16'
    - name: checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: build with Gradle
      run: chmod +x gradlew && ./gradlew build
