name: check PR

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set up JDK 20
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 20
      - name: checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: local merge
        run: git merge --ff-only $GITHUB_HEAD_REF
      - name: build with Gradle
        run: chmod +x gradlew && ./gradlew build testSlow
